### ISSUE TITLE
Sobre o bot do telegram 

### ISSUE THREAD

**Issue by Brayonendryck** [patrick-siotti/projetos_python#1]
ele nao ta enviando uma mensagem para o grupo

**Comment by porfsgabriel** [comment]
Irmão, tu ta enviando mensagem no meu grupo pelo meu bot.
Pra voce fazer o seu procura chama o @botFather no telegram e cria um pra ti e depois troca o token e o id do chat.

**Comment by Brayonendryck** [comment]
Conseguir queria fala com voce tem alguma forma de contato ??

**Comment by Brayonendryck** [comment]
o bot ta enviando essa mensagem ai logo apos manda a mensagem de loos e grenn 

erro no programa principal
erro inesperado:
name 'sec0' is not defined

**Comment by patrick-siotti** [comment]
Cara, eu n tô mechendo em nenhum bot de telegram a muito tempo, n sei se
essa mensagem foi pra mim, mas se sim, então alguém pegou seu token parça

Em qui., 9 de jun. de 2022 3:57 PM, porfsgabriel ***@***.***>
escreveu:

**Comment by Brayonendryck** [comment]
era para voce sim ! , sera mano ?  olha a imagem ai , eu crei esses bot novo nao tem como alguem ta usnado

![image](https://user-images.githubusercontent.com/96250337/173058882-0ea64d62-29ce-4c7a-ad7b-d79f6fa969fe.png)

**Comment by Brayonendryck** [comment]
o bot ele manda vermelho la no site ta dando preto e mesmo assim ele fala que foi green

**Comment by patrick-siotti** [comment]
Vc tá usando meu script né, me chama no discord q eu te mando um script
diferente pra vc testar

Purple-Senpai#7642

Em sex., 10 de jun. de 2022 9:07 AM, Brayonendryck ***@***.***>
escreveu:

**Comment by patrick-siotti** [comment]
Cara, por email é meio foda, não uso muito, me chama por discord:

*Purple-Senpai#7642*

Em sex., 10 de jun. de 2022 1:18 AM, Brayonendryck ***@***.***>
escreveu:
